"""create user and blog table migrations

Revision ID: 760d567ae33d
Revises: bb748308c704
Create Date: 2023-09-27 17:24:54.977784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760d567ae33d'
down_revision = 'bb748308c704'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
